# Node example configuration parameters
  /turtlebot_simulator/run_period: 0.01           # Node execution period
  /turtlebot_simulator/T_a: 0.060                 # Velocity loops constant
  /turtlebot_simulator/a: 6.0                 # Extended unicycle parameter
  /turtlebot_simulator/dt: 0.01                 # Time step
  /turtlebot_simulator/eps: 0.2                 # Epsilon distance from the trajectory